# Generated by Django 5.2.16 on 2026-07-23 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ip', '0001_initial'),
        ('negotiation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_agent_id', models.CharField(max_length=80)),
                ('total_usdc', models.DecimalField(decimal_places=6, max_digits=12)),
                ('status', models.CharField(choices=[('quoted', 'quoted'), ('paid', 'paid'), ('settled', 'settled'), ('partial', 'partial'), ('failed', 'failed')], default='quoted', max_length=20)),
                ('payment_tx_sig', models.CharField(blank=True, max_length=90, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_wallet', models.CharField(db_index=True, max_length=44)),
                ('price_usdc', models.DecimalField(decimal_places=6, max_digits=12)),
                ('usage_type', models.CharField(max_length=30)),
                ('payment_tx_sig', models.CharField(max_length=90, unique=True)),
                ('certificate_tx_sig', models.CharField(blank=True, max_length=90, null=True)),
                ('download_token', models.CharField(blank=True, max_length=64, null=True)),
                ('download_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='ip.ipasset')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='negotiation.negotiationsession')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price_usdc', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='ip.ipasset')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='settlement.batchorder')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_items', to='settlement.license')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoyaltyDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_wallet', models.CharField(max_length=44)),
                ('role', models.CharField(choices=[('original', 'original'), ('secondary', 'secondary')], max_length=20)),
                ('amount_usdc', models.DecimalField(decimal_places=6, max_digits=12)),
                ('transfer_tx_sig', models.CharField(blank=True, max_length=90, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('settled', 'settled'), ('failed', 'failed')], default='pending', max_length=20)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_distributions', to='settlement.license')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['buyer_wallet'], name='settlement__buyer_w_cc5276_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['certificate_tx_sig'], name='settlement__certifi_814ceb_idx'),
        ),
    ]
