# Generated by Django 5.2.16 on 2026-07-23 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_agent_id', models.CharField(max_length=80)),
                ('usage_type', models.CharField(max_length=30)),
                ('initial_offer_usdc', models.DecimalField(decimal_places=6, max_digits=12)),
                ('final_price_usdc', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('negotiating', 'negotiating'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('expired', 'expired')], default='negotiating', max_length=20)),
                ('rounds', models.JSONField(default=list)),
                ('pay_address', models.CharField(blank=True, max_length=44, null=True)),
                ('ap2_cart_mandate', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_sessions', to='ip.ipasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='negotiation_status_b74cf8_idx'), models.Index(fields=['buyer_agent_id'], name='negotiation_buyer_a_b89bbd_idx')],
            },
        ),
    ]
