# Generated by Django 5.2.16 on 2026-07-23 10:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(db_index=True, max_length=44, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IpAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('tags', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
                ('originality_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_price_usdc', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_price_usdc', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('thumbnail_url', models.CharField(max_length=500)),
                ('watermark_url', models.CharField(max_length=500)),
                ('original_url', models.CharField(blank=True, max_length=500, null=True)),
                ('original_expires_at', models.DateTimeField(blank=True, null=True)),
                ('original_purged', models.BooleanField(default=False)),
                ('anchor_tx_sig', models.CharField(blank=True, db_index=True, max_length=90, null=True)),
                ('royalty_share_bps', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('anchored', 'anchored'), ('listed', 'listed'), ('retired', 'retired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='ip.creator')),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivatives', to='ip.ipasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ip_ipasset_status_fca963_idx'), models.Index(fields=['creator'], name='ip_ipasset_creator_295ae3_idx')],
            },
        ),
    ]
