# Generated by Django 5.2.13 on 2026-07-24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ip", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="ipasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("image", "image"), ("document", "document"),
                    ("audio", "audio"), ("video", "video"),
                    ("software", "software"), ("product", "product"),
                    ("other", "other"),
                ],
                db_index=True,
                default="image",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ipasset",
            name="content_mime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ipasset",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipasset",
            name="visibility",
            field=models.CharField(
                choices=[("private", "private"), ("public", "public")],
                db_index=True,
                default="private",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ipasset",
            name="originality_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ipasset",
            name="thumbnail_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ipasset",
            name="watermark_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name="ipasset",
            index=models.Index(
                fields=["visibility", "status", "asset_type"],
                name="ip_ipasset_visibil_df7361_idx",
            ),
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("user", "user"), ("assistant", "assistant")], max_length=12)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assistant_messages", to="ip.creator")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.AddIndex(
            model_name="assistantmessage",
            index=models.Index(fields=["creator", "created_at"], name="ip_assistan_creator_042b78_idx"),
        ),
    ]
