# Generated by Django 5.2.16 on 2026-07-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ip", "0002_public_catalog_and_assistant")]

    operations = [
        migrations.CreateModel(
            name="CreatorExpense",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount_usdc", models.DecimalField(decimal_places=6, max_digits=12)),
                ("memo", models.CharField(max_length=200)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="ip.creator")),
            ],
            options={"ordering": ["-occurred_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="creatorexpense",
            index=models.Index(fields=["creator", "occurred_at"], name="ip_expense_creator_9e34bc_idx"),
        ),
    ]
