# Generated by Django 5.2.16 on 2026-07-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ip", "0003_creator_expense")]

    operations = [
        migrations.CreateModel(
            name="AgentDirective",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("instruction", models.TextField(max_length=2000)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_directives",
                        to="ip.creator",
                    ),
                ),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="agentdirective",
            index=models.Index(
                fields=["creator", "is_active", "updated_at"],
                name="ip_directive_creator_idx",
            ),
        ),
    ]
