# Generated by Django 5.2.16 on 2026-07-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ip", "0004_agent_directive")]

    operations = [
        migrations.CreateModel(
            name="AssistantAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action_name", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "completed"),
                            ("awaiting_input", "awaiting_input"),
                            ("rejected", "rejected"),
                            ("failed", "failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("request_payload", models.JSONField(default=dict)),
                ("result_payload", models.JSONField(default=dict)),
                ("verification_passed", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_actions",
                        to="ip.creator",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="ip.assistantmessage",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="assistantaction",
            index=models.Index(fields=["creator", "created_at"], name="ip_action_creator_idx"),
        ),
    ]
