# Generated by Django 5.2.13 on 2026-07-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0005_assistant_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "monthly_fee_usdc",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("included_registrations", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CreatorSubscription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("expired", "expired")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("payment_tx_sig", models.CharField(max_length=140, unique=True)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("registrations_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="ip.creator",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="ip.subscriptionplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationCharge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_charge",
                        to="ip.ipasset",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_charges",
                        to="ip.creatorsubscription",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="creatorsubscription",
            index=models.Index(
                fields=["creator", "status", "period_end"],
                name="ip_sub_creator_status_idx",
            ),
        ),
    ]
