# Generated by Django 5.2.13 on 2026-07-24 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0006_subscription_billing"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collecting", "collecting"),
                            ("confirmed", "confirmed"),
                            ("executed", "executed"),
                        ],
                        default="collecting",
                        max_length=16,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_sha256", models.CharField(blank=True, max_length=64)),
                ("fields", models.JSONField(default=dict)),
                (
                    "confirmation_token",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_drafts",
                        to="ip.creator",
                    ),
                ),
                (
                    "executed_asset",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_draft",
                        to="ip.ipasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["creator", "status", "updated_at"],
                        name="ip_draft_creator_status_idx",
                    )
                ],
            },
        ),
    ]
