# Generated by Django 5.2.13 on 2026-07-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0007_registrationdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipasset",
            name="perceptual_hash",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
