# Generated by Django 5.2.13 on 2026-07-24 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0008_perceptual_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("content_mime_type", models.CharField(max_length=100)),
                ("content_sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "perceptual_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, null=True
                    ),
                ),
                ("temporary_url", models.CharField(max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("analysis", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_attachments",
                        to="ip.creator",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="ip.assistantmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["creator", "created_at"], name="ip_attach_creator_idx"
                    )
                ],
            },
        ),
    ]
