# Generated by Django 5.2.13 on 2026-07-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0009_conversation_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipasset",
            name="registration_certificate_tx_sig",
            field=models.CharField(blank=True, db_index=True, max_length=90, null=True),
        ),
    ]
