# Generated by Django 5.2.13 on 2026-07-24

import uuid

from django.db import migrations, models


def assign_existing_conversations(apps, schema_editor):
    """기존 메시지는 사용자 발화와 뒤따르는 응답을 하나의 세션으로 묶는다."""
    AssistantMessage = apps.get_model("ip", "AssistantMessage")
    creator_ids = AssistantMessage.objects.values_list("creator_id", flat=True).distinct()
    for creator_id in creator_ids.iterator():
        current = None
        for message in AssistantMessage.objects.filter(creator_id=creator_id).order_by("created_at", "id"):
            if message.role == "user" or current is None:
                current = uuid.uuid4()
            message.conversation_id = current
            message.save(update_fields=["conversation_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0010_registration_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantmessage",
            name="conversation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(assign_existing_conversations, migrations.RunPython.noop),
    ]
