# Generated by Django 5.2.16 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0012_asset_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantmessage",
            name="conversation_title",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
