# Generated by Django 5.2.16 on 2026-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0013_assistant_message_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipasset',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipasset',
            name='ai_tags',
            field=models.JSONField(default=list),
        ),
    ]
