# Generated by Django 5.2.16 on 2026-07-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0014_ipasset_ai_description_ipasset_ai_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ipasset",
            name="account_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="library_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
