# Generated by Django 5.2.10 on 2026-08-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ip", "0021_sponsoredpaymentintent_channel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsoredpaymentintent",
            name="buyer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sponsored_payment_intents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
