# Generated by Django 5.2.16 on 2026-07-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ip', '0001_initial'),
        ('negotiation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ip.ipasset')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='negotiation.negotiationsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='common_agen_type_6c2fb8_idx'), models.Index(fields=['asset', 'created_at'], name='common_agen_asset_i_c55003_idx')],
            },
        ),
    ]
