# Generated by Django 5.2.16 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="recovery_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
