# Generated by Django 5.2.16 on 2026-07-24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0002_userpreference_recovery_contact")]

    operations = [
        migrations.CreateModel(
            name="WalletConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=64)),
                ("accepts_deposits", models.BooleanField(default=True)),
                ("receives_payouts", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="wallet_configurations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-is_active", "-created_at"]},
        ),
        migrations.AddConstraint(model_name="walletconfiguration", constraint=models.UniqueConstraint(fields=("user", "address"), name="accounts_wallet_per_user_address")),
    ]
