# Generated by Django 5.2.5 on 2026-07-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_prepare_creator_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletconfiguration',
            name='private_address',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
